version: 2
jobs:
  build:
    docker:
      - image: arekczarnik/docker-circleci-haskell:latest
    branches:
      only:
        - hakyll
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ checksum "blog.cabal" }}-{{ checksum "stack.yaml" }}
      - run: stack build --fast --no-terminal
      - save_cache:
          key: deps1-{{ checksum "blog.cabal" }}-{{ checksum "stack.yaml" }}
          paths:
            ~/.stack
            ./.stack-work
      - deploy:
          name: Deploy master to GitHub Pages
          command: |
            git config --global user.email robots@circleci.com
            git config --global user.name CircleCI
            stack exec blog rebuild
            cp .gitignore _site/
            commit=$(git rev-parse HEAD)
            echo In response to commit ${commit}
            git checkout master
            echo checked out master
            git pull
            echo pulled
            cp -a _site/. .
            echo copied
            git add --all
            echo added
            git commit -m "[$(date '+%F %T %Z')] New release in response to commit ${commit}"
            echo committed
            git push origin master:master
            echo pushed
