version: 2
jobs:
  build:
    docker:
      - image: futtetennista/hakyll:4.9.8.0
    branches:
      only:
        - hakyll
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ checksum "blog.cabal" }}-{{ checksum "stack.yaml" }}
      - run: stack build --fast --no-terminal
      - save_cache:
          key: deps1-{{ checksum "blog.cabal" }}-{{ checksum "stack.yaml" }}
          paths:
            ~/.stack
            ./.stack-work
      - deploy:
          name: Deploy master to GitHub Pages
          command: |
            git config --global user.email robots@circleci.com
            git config --global user.name CircleCI
            stack exec blog rebuild
            cp .gitignore _site/
            commit=$(git rev-parse HEAD)
            git checkout master
            git pull --rebase
            cp -a _site/. .
            git add --all
            git commit -m "[$(date '+%F %T %Z')] New release in response to commit ${commit}"
            git push origin master:master
